from enum import Enum


class State(str, Enum):
    IDEA = "IDEA"
    RESEARCHING = "RESEARCHING"
    RESEARCH_COMPLETE = "RESEARCH_COMPLETE"
    FACT_CHECKING = "FACT_CHECKING"
    FACT_CHECK_COMPLETE = "FACT_CHECK_COMPLETE"
    SCRIPTING = "SCRIPTING"
    SCRIPT_COMPLETE = "SCRIPT_COMPLETE"
    STORYBOARDING = "STORYBOARDING"
    ASSET_GENERATION = "ASSET_GENERATION"
    VOICE_GENERATION = "VOICE_GENERATION"
    RENDERING = "RENDERING"
    QA = "QA"
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    NOTIFIED = "NOTIFIED"
    REGENERATING = "REGENERATING"
    FAILED = "FAILED"


S = State

PRODUCTION_ORDER = [
    S.IDEA, S.RESEARCHING, S.RESEARCH_COMPLETE, S.FACT_CHECKING, S.FACT_CHECK_COMPLETE,
    S.SCRIPTING, S.SCRIPT_COMPLETE, S.STORYBOARDING, S.ASSET_GENERATION, S.VOICE_GENERATION,
    S.RENDERING, S.QA, S.READY_FOR_DELIVERY, S.DELIVERED, S.NOTIFIED,
]

TRANSITIONS: dict[State, set[State]] = {a: {b} for a, b in zip(PRODUCTION_ORDER, PRODUCTION_ORDER[1:])}
TRANSITIONS[S.NOTIFIED] = {S.REGENERATING}
TRANSITIONS[S.DELIVERED] |= {S.REGENERATING}
TRANSITIONS[S.REGENERATING] = {S.SCRIPT_COMPLETE, S.SCRIPTING, S.ASSET_GENERATION, S.VOICE_GENERATION, S.RENDERING}
TRANSITIONS[S.FAILED] = (set(PRODUCTION_ORDER) - {S.NOTIFIED}) | {S.REGENERATING}

for _s in State:
    if _s not in (S.FAILED, S.NOTIFIED):
        TRANSITIONS.setdefault(_s, set()).add(S.FAILED)


class IllegalTransition(Exception):
    pass


def check_transition(src: State, dst: State) -> None:
    if dst not in TRANSITIONS.get(src, set()):
        raise IllegalTransition(f"{src.value} -> {dst.value}")
